config/routes.rb
Rails.application.routes.draw do
  root 'albums#index'
  get 'albums' => 'albums#index'
  get 'albums/new' => 'albums#new'
  get 'albums/:id' => 'albums#show', as: :album
  post 'albums' => 'albums#create'
  
  get 'signup'  => 'users#new' 
  resources :users
  
  get '/login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

end

app/models/album.rb
class Album < ActiveRecord::Base

  has_many :photos

end

app/models/photo.rb
class Photo < ActiveRecord::Base

  belongs_to :album

end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

end

app/controllers/.1_4_users_controller.rb
class UsersController < ApplicationController
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
	before_action :require_user, only: [:index, :show]
  def index
    @albums = Album.all
  end 

  def show
    @album = Album.find(params[:id])
    @photos = @album.photos
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user 

	def current_user 
	  @current_user ||= User.find(session[:user_id]) if session[:user_id] 
	end
	
	def require_user 
	  redirect_to '/login' unless current_user 
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
	  @user = User.find_by_email(params[:session][:email])
	  if @user && @user.authenticate(params[:session][:password])
	    session[:user_id] = @user.id
	    redirect_to '/'
	  else
	    redirect_to 'login'
	  end 
	end
	
	def destroy 
	  session[:user_id] = nil 
	  redirect_to '/' 
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

	def create 
	  @user = User.new(user_params) 
	  if @user.save 
	    session[:user_id] = @user.id 
	    redirect_to '/' 
	  else 
	    redirect_to '/signup' 
	  end 
	end  

	private
	  def user_params
	    params.require(:user).permit(:first_name, :last_name, :email, :password)
	  end  
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/albums/index.html.erb
<div class="albums">
  <div class="container">

    <div class="row">
      <% @albums.each do |album|%> 
        <div class="item col-md-4">
          <div class="img-container">
            <%= image_tag album.image %>
          </div>
          <div class="album-info">
            <h2><%= album.title %></h2> 
            <p><%= link_to "See Album", album_path(album) %></p>
          </div>
        </div>
      <% end %> 
    </div>

  </div>
</div>

app/views/albums/show.html.erb
<div class="photos">
  <div class="container">

    <h1><%= @album.title %></h1>
    <div class="row">
      <% @photos.each do |photo|%> 
        <div class="item col-md-4">
          <div class="img-container">
            <%= image_tag photo.image %>
          </div>
          <div class="photo-info">
            <p><%= photo.caption %></p> 
          </div>
        </div>
      <% end %> 
    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <link href="http://s3.amazonaws.com/codecademy-content/projects/bootstrap.min.css" rel="stylesheet" />
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,500,300' rel='stylesheet' type='text/css'>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <div class="header">
      <div class="container">
        <%= link_to root_path do %>
          <img src="http://s3.amazonaws.com/codecademy-content/courses/rails-auth/img/fotofoto-logo.svg" width="80" height="80"> &#12501; &#65387; &#12488; &#12501; &#65387; &#12488;
        <% end %>

        <div class="nav pull-right">
          <% if current_user %> 
  <ul> 
    <li><%= current_user.email %></li> 
    <li><%= link_to "Log out", logout_path, method: "delete" %></li> 
  </ul> 
<% else %> 
  <ul> 
    <li><%= link_to "Login", 'login' %></a></li> 
    <li><%= link_to "Signup", 'signup' %></a></li> 
  </ul> 
<% end %>
          
        </div>
      </div>
    </div>

    <%= yield %>

  </body>
</html>

app/views/users/.1_4_new.html.erb
<div class="login">
  <div class="container">
    <div class="form">

    <h1>Sign up</h1>


  
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="login">
  <div class="container">
    <div class="form">

    <h1>Sign up</h1>

    <%= form_for(@user) do |f| %>
      <%= f.text_field :first_name, :placeholder => "First name" %>
      <%= f.text_field :last_name, :placeholder => "Last name" %>
      <%= f.email_field :email, :placeholder => "Email" %>
      <%= f.password_field :password, :placeholder => "Password" %>
      <%= f.submit "Create an account", class: "btn-submit" %>
    <% end %>

  
    </div>
  </div>
</div>